import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { ArrowLeft, Loader2, MessageSquare, Calendar, FileText, RefreshCw, Info } from 'lucide-react';
import { toast } from 'sonner';
import { formatCurrencyBRL } from '@/lib/EliteScoreEngine';

export default function ScoreElite() {
  const qc = useQueryClient();
  const [filters, setFilters] = useState({ cidade: '', classificacao: 'all', produto: 'all', acao: 'all', visita: 'all' });
  const { data: scores = [], isLoading } = useQuery({ queryKey: ['score-elite-list'], queryFn: () => base44.entities.EliteLeadScore.list('-elite_score', 300), staleTime: 60000 });
  const activate = useMutation({ mutationFn: () => base44.functions.invoke('activateEliteScore', {}), onSuccess: (res) => { qc.invalidateQueries({ queryKey: ['score-elite-list'] }); toast.success(`Score Elite atualizado: ${res.data?.total_analisado || 0} analisados`); } });
  const filtered = useMemo(() => scores.filter(s => (!filters.cidade || s.cidade?.toLowerCase().includes(filters.cidade.toLowerCase())) && (filters.classificacao === 'all' || s.classificacao_score === filters.classificacao) && (filters.produto === 'all' || s.produto_recomendado === filters.produto) && (filters.acao === 'all' || s.proxima_melhor_acao === filters.acao) && (filters.visita === 'all' || (filters.visita === 'alta' ? (s.prioridade_visita || 0) >= 75 : (s.prioridade_visita || 0) < 75))), [scores, filters]);
  const products = [...new Set(scores.map(s => s.produto_recomendado).filter(Boolean))];
  const actions = [...new Set(scores.map(s => s.proxima_melhor_acao).filter(Boolean))];
  const generateMessage = async (s) => { const res = await base44.functions.invoke('gerarMensagemElite', { cliente_id: s.cliente_id, lead_id: s.lead_id, score_id: s.id }); toast.success(`PendingMessage criado: ${res.data?.status}`); };

  return <div className="min-h-screen bg-black text-white p-4 pb-24"><div className="max-w-5xl mx-auto space-y-4">
    <div className="flex items-center gap-3"><Link to="/"><Button size="icon" variant="outline"><ArrowLeft className="w-4 h-4" /></Button></Link><div className="flex-1"><h1 className="text-2xl font-black text-orange-400">Score Elite</h1><p className="text-xs text-orange-200">Ranking real por EliteLeadScore</p></div><Button onClick={() => activate.mutate()} disabled={activate.isPending} className="bg-orange-600 hover:bg-orange-500">{activate.isPending ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <RefreshCw className="w-4 h-4 mr-2" />}Ativar Score Elite</Button></div>
    <div className="grid md:grid-cols-5 gap-2"><Input placeholder="Cidade" value={filters.cidade} onChange={e => setFilters({ ...filters, cidade: e.target.value })} className="bg-[#111] border-orange-500/30" /><Select value={filters.classificacao} onValueChange={v => setFilters({ ...filters, classificacao: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Classificação</SelectItem>{['frio','aquecer','oportunidade','quente','fechamento_imediato'].map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={filters.produto} onValueChange={v => setFilters({ ...filters, produto: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Produto</SelectItem>{products.map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={filters.acao} onValueChange={v => setFilters({ ...filters, acao: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Ação</SelectItem>{actions.map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={filters.visita} onValueChange={v => setFilters({ ...filters, visita: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Visita</SelectItem><SelectItem value="alta">Prioridade alta</SelectItem><SelectItem value="baixa">Prioridade baixa</SelectItem></SelectContent></Select></div>
    {isLoading ? <div className="p-10 text-center"><Loader2 className="w-8 h-8 animate-spin mx-auto text-orange-400" /></div> : filtered.length === 0 ? <Card className="p-8 bg-[#111] border-orange-500/20 text-center text-orange-100">Score Elite ainda não calculado. Clique em Ativar Score Elite.</Card> : <div className="grid lg:grid-cols-2 gap-3">{filtered.map((s, idx) => <Card key={s.id} className="p-4 bg-[#111] border-orange-500/25 text-white"><div className="flex items-start justify-between gap-3"><div><Badge className="bg-orange-600 mb-2">#{idx + 1} · {s.classificacao_score}</Badge><h3 className="font-black text-lg">{s.cidade || 'Sem cidade'} · {s.produto_recomendado || 'Produto pendente'}</h3><p className="text-xs text-slate-400">{s.motivo_score}</p></div><div className="text-right"><p className="text-3xl font-black text-orange-400">{s.elite_score}</p><p className="text-[10px] text-slate-500">score</p></div></div><div className="grid grid-cols-3 gap-2 my-3 text-xs"><Mini label="Fechamento" value={`${s.chance_fechamento || 0}%`} /><Mini label="Valor" value={formatCurrencyBRL(s.valor_estimado)} /><Mini label="Visita" value={s.prioridade_visita || 0} /></div><p className="text-sm text-orange-100 mb-3">Próxima ação: <b>{s.proxima_melhor_acao}</b></p><div className="grid grid-cols-2 gap-2"><Button size="sm" onClick={() => generateMessage(s)}><MessageSquare className="w-4 h-4 mr-1" />Gerar mensagem</Button><Button size="sm" variant="outline" onClick={() => toast.info('Gere a mensagem, aprove na fila do WhatsApp Hub e envie manualmente.')}><Info className="w-4 h-4 mr-1" />Como enviar</Button><Link to={`/ProposalGenerator?client_id=${s.cliente_id || ''}`}><Button size="sm" variant="outline" className="w-full"><FileText className="w-4 h-4 mr-1" />Proposta</Button></Link><Link to={`/VisitManager?client_id=${s.cliente_id || ''}`}><Button size="sm" variant="outline" className="w-full"><Calendar className="w-4 h-4 mr-1" />Visita</Button></Link></div><p className="text-[10px] text-slate-500 mt-2">Atualizado: {s.data_atualizacao ? new Date(s.data_atualizacao).toLocaleString('pt-BR') : '—'}</p></Card>)}</div>}
  </div></div>;
}
function Mini({ label, value }) { return <div className="rounded-xl p-2 bg-black/40 border border-orange-500/10"><p className="text-[10px] text-orange-300">{label}</p><p className="font-black truncate">{value}</p></div>; }